### ISSUE TITLE
Feature request: display context if no characters 

### ISSUE THREAD

**Issue by funkyfuture** [jamischarles/atom-todo-show#54]
suppose you annotate your code in some situations, like this:

    do_something  # DEBUG

or 

    class some_class():
      def __init__(self):
        pass  # TODO

just to point at something.

and define a regex like `/TODO:?($|(.+$))/g`, todo-show will also find these TODOs. but as the match-group is empty, show no context.

i propose it should in that case print the content before the match, exluding leading non-alphanumeric chars and an comment-delimiter at the end.

an approach could be to extend the regex before the searched token in question. thus todo-show just needed to prefer a non-empty, second match-group as token-context.

**Comment by MRodalgaard** [comment]
I like the idea, though I think it is an anti-pattern to write a todo without extra information.

It can actually be solved with the current solution via something similar to the config below:
```
"todo-show":
  findTheseRegexes: [
    "pre-TODOs"
    "/(.+?(?=.{2}TODO\\s*$))/"
    "TODOs"
    "/TODO:?(.+$)/g"
  ]
```

`.+?` all content up till next section.
`(?=.{2}TODO\\s*$)` non-capture, two characters, TODO, white-spaces, end of line.
`()` extra capture because we are using the 2nd match for the result.

Try it. The default TODO regex does not capture this unless there is a leading white-space.

**Comment by mrodalgaard** [comment]
I am closing this due to missing addional information. And I do not think it is relavent enough.

**Comment by mrodalgaard** [comment]
The default regex now shows ending todos like described above, but with "No details" as text.

The full solution would require some extended logic behind the screnes or a really advanced regex for each todo group.

**Comment by funkyfuture** [comment]
thanks for the update.
