### ISSUE TITLE
Feature: hide file path and just have message of todo or fixme

### ISSUE THREAD

**Issue by mediabeastnz** [jamischarles/atom-todo-show#62]

**Comment by mrodalgaard** [comment]
I need some additional details on this:
1. In what scenario would this be useful? Just to declutter?
2. Would you want this as a config option? What would you call this option?
3. Are we talking about the normal pane list or the saved markdown output?

**Comment by mrodalgaard** [comment]
Closed because of missing additional information.

The new grouping config `todo-show.groupMatchesBy` helps a little in decluttering according to the specific user needs. I think the view is pretty compact as is, unless you write essays as todos and fixmes.

I will gladly reopen the ticket if more people are interested.
