### ISSUE TITLE
Reorganize result

### ISSUE THREAD

**Issue by anion155** [jamischarles/atom-todo-show#66]
I think it would be nicer if results of searching todos would be grouped by files, and sorted by type (regexp).

**Comment by mrodalgaard** [comment]
I love this. I will make this into a string array option: `enum: ['regex', 'file']`. Hopefully done by today.

**Comment by avnarun** [comment]
@jamischarles - first of all thanks a lot for the great package. I just installed it for the first time and already loving it. 

I was trying the same thing as being discussed here, ie is to sort by type (todo, fixme etc), so that I can look at list of different files pending my work .. I will watch this thread and I will also try to poke around if I can get to do this.

**Comment by mrodalgaard** [comment]
6ae93994f29a0738a75e9b1883c173245c3e153c includes configurable grouping. I will add a description to the readme soon.

I would very much like somebody to also test this, since I have changed a lot of internal code for this to be implemented nicely.

**Comment by mrodalgaard** [comment]
Included in 0.14.0 release using the `todo-show.groupMatchesBy` config.
