### ISSUE TITLE
Custom Ignore-Paths are not Ignored

### ISSUE THREAD

**Issue by Hoff97** [jamischarles/atom-todo-show#79]
Putting any paths in the configuration of the package itself wont make it ignore these paths when searching for matches. However adding these into the Atom core ignored names works just fine.

**Comment by mrodalgaard** [comment]
I believe it should be fixed in the newest release, where I changed the implementation to use `atom.workspace.scan` paths argument instead of the ignore module. Internally Atom uses [scandal](https://github.com/atom/scandal) for directory scanning and searching. The same as [find-and-replace](https://github.com/atom/find-and-replace) uses.
